name: Responder Issues
on:
  issues:
    types: [opened]

jobs:
  responder:
    runs-on: ubuntu-latest
    steps:
      - name: Responder à Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context } = require('@actions/github'); 
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Olá! Obrigado por abrir esta issue. Nossa equipe analisará e responderá em breve. 🚀"
            });

